# Generated by Django 5.0 on 2025-11-11 18:30
from django.db import migrations

def copy_data(apps, schema_editor):
    OldAddress = apps.get_model('oc_lettings_site', 'Profile')
    NewAddress = apps.get_model('profiles', 'Profile')
    
   
    for old_addr in OldAddress.objects.all():
        NewAddress.objects.create(
            user=old_addr.user,
            favorite_city=old_addr.favorite_city
        )

class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("oc_lettings_site", "__first__"),
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]
