# Generated by Django 5.0 on 2025-11-11 15:49

from django.db import migrations

def copy_data(apps, schema_editor):
    # Récupère les anciens modèles
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    # Récupère les nouveaux modèles
    NewAddress = apps.get_model('lettings', 'Address')
    Oldletting = apps.get_model('oc_lettings_site', 'Letting')
    NewLetting = apps.get_model('lettings', 'Letting')
    
   
    for old_addr in OldAddress.objects.all():
        NewAddress.objects.create(
            id=old_addr.id,
            number=old_addr.number,
            street=old_addr.street,
            city=old_addr.city,
            state=old_addr.state,
            zip_code=old_addr.zip_code,
            country_iso_code=old_addr.country_iso_code
        )
    
    for old_lett in Oldletting.objects.all():
        NewLetting.objects.create(
            title= old_lett.title,
            address=NewAddress.objects.get(id=old_lett.address.id)
        )
    

class Migration(migrations.Migration):
    dependencies = [
        ("lettings", "0001_initial"),
        ("oc_lettings_site", "__first__"),  # Important !
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]